# Generated by Django 3.0.3 on 2020-02-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_count', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('bedroom_count', models.IntegerField()),
                ('home_size', models.IntegerField(blank=True, null=True)),
                ('home_type', models.CharField(choices=[('AP', 'Apartment'), ('CO', 'Condominium'), ('DX', 'Duplex'), ('MX', 'Miscellaneous'), ('MF', 'MultiFamily2To4'), ('SF', 'SingleFamily'), ('VR', 'VacantResidentialLand')], max_length=2)),
                ('property_size', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('last_sold', models.DateField(blank=True, null=True)),
                ('last_sold_price', models.IntegerField(blank=True, null=True)),
                ('listing_price', models.IntegerField()),
                ('listing_link', models.URLField()),
                ('rent_price', models.IntegerField(blank=True, null=True)),
                ('rentzestimate_amount', models.IntegerField(blank=True, null=True)),
                ('rentzestimate_last_updated', models.DateField(blank=True, null=True)),
                ('tax_value', models.IntegerField()),
                ('tax_year', models.IntegerField()),
                ('zestimate_amount', models.IntegerField(blank=True, null=True)),
                ('zestimate_last_updated', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
            ],
        ),
    ]
