# Generated by Django 3.0.3 on 2020-02-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='bathroom_count',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='bedroom_count',
            new_name='bedrooms',
        ),
        migrations.AddField(
            model_name='house',
            name='zillow_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
